# panorama management password configuration snippets

name: panorama_mgt_config_pwd_10_1
label: Panorama Mgt Password Config
description: |-
    reference management password configuration snippets
type: panorama
labels:
    collection:
      - IronSkillet 10.1 Panorama Snippets

variables:


snippets:

-   name: ironskillet_password_complexity
    xpath: /config/mgt-config/password-complexity
    element: |-
      <enabled>yes</enabled>
      <minimum-length>12</minimum-length>
      <minimum-uppercase-letters>1</minimum-uppercase-letters>
      <minimum-lowercase-letters>1</minimum-lowercase-letters>
      <minimum-numeric-letters>1</minimum-numeric-letters>
      <minimum-special-characters>1</minimum-special-characters>
      <block-username-inclusion>yes</block-username-inclusion>
      <password-history-count>24</password-history-count>
      <new-password-differs-by-characters>3</new-password-differs-by-characters>