# panorama management users configuration snippets

name: panorama_mgt_config_users_10_0
label: Panorama Mgt Users Config
description: |-
    reference management users configuration snippets
type: panorama
labels:
    collection:
      - IronSkillet 10.0 Panorama Snippets

variables:

  - name: ADMINISTRATOR_USERNAME
    description: admin username
    default: adminuser
    type_hint: text
    help_text: if the user opts out of the Panorama admin config, this user will still be applied as a firewall adminstrator
  - name: ADMINISTRATOR_PASSWORD
    description: admin password
    default: adminuser
    type_hint: password
    help_text: if the user opts out of the Panorama admin config, this password will still be applied to the firewall administrator

snippets:

-   name: ironskillet_mgmt_config_users
    xpath: /config/mgt-config/users
    element: |-
      <entry name="{{ ADMINISTRATOR_USERNAME }}">
        <phash>{{ ADMINISTRATOR_PASSWORD | md5_hash }}</phash>
        <permissions>
          <role-based>
            <superuser>yes</superuser>
          </role-based>
        </permissions>
      </entry>