# panorama device management configuration snippets

name: panorama_device_mgt_config_10_0
label: Panorama Device - Mgt Config
description: |-
    reference device management configuration snippets
type: panorama
labels:
    collection:
      - IronSkillet 10.0 Panorama Snippets

variables:

  - name: ADMINISTRATOR_USERNAME
    description: admin username
    default: adminuser
    type_hint: text
    help_text: if the user opts out of the Panorama admin config, this user will still be applied as a firewall adminstrator
  - name: ADMINISTRATOR_PASSWORD
    description: admin password
    default: adminuser
    type_hint: password
    help_text: if the user opts out of the Panorama admin config, this password will still be applied to the firewall administrator

snippets:

-   name: ironskillet_device_mgt_users
    xpath: /config/devices/entry[@name='localhost.localdomain']/template/entry[@name='iron-skillet']/config/mgt-config
    element: |-
      <users>
        <entry name="{{ ADMINISTRATOR_USERNAME }}">
          <phash>{{ ADMINISTRATOR_PASSWORD | md5_hash }}</phash>
          <permissions>
            <role-based>
              <superuser>yes</superuser>
            </role-based>
          </permissions>
        </entry>
      </users>

-   name: ironskillet_device_mgt_password_complexity
    xpath: /config/devices/entry[@name='localhost.localdomain']/template/entry[@name='iron-skillet']/config/mgt-config
    element: |-
      <password-complexity>
        <enabled>yes</enabled>
        <minimum-length>12</minimum-length>
        <minimum-uppercase-letters>1</minimum-uppercase-letters>
        <minimum-lowercase-letters>1</minimum-lowercase-letters>
        <minimum-numeric-letters>1</minimum-numeric-letters>
        <minimum-special-characters>1</minimum-special-characters>
        <block-username-inclusion>yes</block-username-inclusion>
        <password-history-count>24</password-history-count>
        <new-password-differs-by-characters>3</new-password-differs-by-characters>
      </password-complexity>