# panorama log settings configuration snippets

name: panorama_log_settings_10_0
label: Panorama Log Settings
description: |-
    reference log settings configuration snippets
type: panorama
labels:
    collection:
      - IronSkillet 10.0 Panorama Snippets

variables:

  - name: EMAIL_PROFILE_GATEWAY
    description: email gateway address for critical alerts
    default: 192.0.2.1
    type_hint: text
    help_text: email server profile configuration under Device --> Server Profiles
  - name: EMAIL_PROFILE_FROM
    description: from address in email alerts
    default: sentfrom@yourdomain.com
    type_hint: text
    help_text: email server profile configuration under Device --> Server Profiles
  - name: EMAIL_PROFILE_TO
    description: to address in email alerts
    default: sendto@yourdomain.com
    type_hint: text
    help_text: email server profile configuration under Device --> Server Profiles
  - name: SYSLOG_SERVER
    description: syslog server ip address
    default: 192.0.2.2
    type_hint: text

snippets:
-   name: ironskillet_log_settings_email_profile
    xpath: /config/panorama/log-settings
    element: |-
      <email>
        <entry name="Sample_Email_Profile">
          <server>
            <entry name="Sample_Email_Profile">
              <display-name>Threat_Alerts</display-name>
              <gateway>{{ EMAIL_PROFILE_GATEWAY }}</gateway>
              <from>{{ EMAIL_PROFILE_FROM }}</from>
              <to>{{ EMAIL_PROFILE_TO }}</to>
              <protocol>SMTP</protocol>
            </entry>
          </server>
        </entry>
      </email>

-   name: ironskillet_log_settings_syslog_profile
    xpath: /config/panorama/log-settings
    element: |-
      <syslog>
        <entry name="Sample_Syslog_Profile">
          <server>
            <entry name="Sample_Syslog">
              <transport>UDP</transport>
              <port>514</port>
              <format>BSD</format>
              <server>{{ SYSLOG_SERVER }}</server>
              <facility>LOG_USER</facility>
            </entry>
          </server>
        </entry>
      </syslog>

-   name: ironskillet_log_settings_critical_system
    xpath: /config/panorama/log-settings
    element: |-
      <system>
        <match-list>
          <entry name="Critical_System_Log_Email">
            <send-email>
              <member>Sample_Email_Profile</member>
            </send-email>
            <filter>(severity eq critical)</filter>
          </entry>
          <entry name="System_Log_Forwarding">
            <send-syslog>
              <member>Sample_Syslog_Profile</member>
            </send-syslog>
            <filter>All Logs</filter>
          </entry>
        </match-list>
      </system>

-   name: ironskillet_log_settings_log_forwarding
    xpath: /config/panorama/log-settings
    element: |-
      <config>
        <match-list>
          <entry name="Configuration_Log_Forwarding">
            <send-syslog>
              <member>Sample_Syslog_Profile</member>
            </send-syslog>
            <filter>All Logs</filter>
          </entry>
        </match-list>
      </config>

-   name: ironskillet_log_settings_userid_forwarding
    xpath: /config/panorama/log-settings
    element: |-
      <userid>
        <match-list>
          <entry name="User-ID_Log_Forwarding">
            <send-syslog>
              <member>Sample_Syslog_Profile</member>
            </send-syslog>
            <filter>All Logs</filter>
          </entry>
        </match-list>
      </userid>