# panos shared log settings configuration snippets

name: panos_ngfw_shared_log_settings_email_system_critical_10_0
label: PAN_OS NGFW Shared Log Settings - Email System Critical
description: |-
    reference shared log settings email system critical configuration snippets
type: panos
labels:
    collection:
      - IronSkillet 10.0 PAN-OS Snippets

variables:


snippets:

-   name: ironskillet_shared_log_settings_email_system_critical
    xpath: /config/shared/log-settings/system/match-list
    element: |-
       <entry name="Email_Critical_System_Logs">
            <send-email>
              <member>Sample_Email_Profile</member>
            </send-email>
            <filter>(severity eq critical)</filter>
            <description>Email Critical System Logs</description>
       </entry>