# panos shared log settings configuration snippets

name: panos_ngfw_shared_log_settings_orig_10_0
label: PAN_OS NGFW Shared Log Settings - Orig
description: |-
    reference shared log settings configuration snippets
type: panos
labels:
    collection:
      - IronSkillet 10.0 PAN-OS Snippets

variables:

  - name: EMAIL_PROFILE_GATEWAY
    description: email gateway address for critical alerts
    default: 192.0.2.1
    type_hint: text
    help_text: email server profile configuration under Device --> Server Profiles
  - name: EMAIL_PROFILE_FROM
    description: from address in email alerts
    default: sentfrom@yourdomain.com
    type_hint: text
    help_text: email server profile configuration under Device --> Server Profiles
  - name: EMAIL_PROFILE_TO
    description: to address in email alerts
    default: sendto@yourdomain.com
    type_hint: text
    help_text: email server profile configuration under Device --> Server Profiles
  - name: SYSLOG_SERVER
    description: syslog server ip address
    default: 192.0.2.2
    type_hint: text

snippets:

-   name: ironskillet_shared_log_settings_sample_email_profile
    xpath: /config/shared/log-settings
    element: |-
      <email>
        <entry name="Sample_Email_Profile">
          <server>
            <entry name="Sample_Email_Profile">
              <display-namesample_server_name</display-name>
              <gateway>{{ EMAIL_PROFILE_GATEWAY }}</gateway>
              <from>{{ EMAIL_PROFILE_FROM }}</from>
              <to>{{ EMAIL_PROFILE_TO }}</to>
            </entry>
          </server>
        </entry>
      </email>

-   name: ironskillet_shared_log_settings_syslog_profile
    xpath: /config/shared/log-settings
    element: |-
      <syslog>
        <entry name="Sample_Syslog_Profile">
          <server>
            <entry name="Sample_Syslog">
              <transport>UDP</transport>
              <port>514</port>
              <format>BSD</format>
              <server>{{ SYSLOG_SERVER }}</server>
              <facility>LOG_USER</facility>
            </entry>
          </server>
        </entry>
      </syslog>

-   name: ironskillet_shared_log_settings_email_syslog_forwarding
    xpath: /config/shared/log-settings
    element: |-
      <system>
        <match-list>
          <entry name="Email_Critical_System_Logs">
            <send-email>
              <member>Sample_Email_Profile</member>
            </send-email>
            <filter>(severity eq critical)</filter>
            <description>Email Critical System Logs</description>
          </entry>
          <entry name="System_Log_Forwarding">
            <filter>All Logs</filter>
            <send-to-panorama>no</send-to-panorama>
            <send-syslog>
              <member>Sample_Syslog_Profile</member>
            </send-syslog>
          </entry>
        </match-list>
      </system>

-   name: ironskillet_shared_log_settings_configuration_forwarding
    xpath: /config/shared/log-settings
    element: |-
      <config>
        <match-list>
          <entry name="Configuration_Log_Forwarding">
            <filter>All Logs</filter>
            <send-to-panorama>no</send-to-panorama>
            <send-syslog>
              <member>Sample_Syslog_Profile</member>
            </send-syslog>
          </entry>
        </match-list>
      </config>

-   name: ironskillet_shared_log_settings_userid_forwarding
    xpath: /config/shared/log-settings
    element: |-
      <userid>
        <match-list>
          <entry name="User-ID_Log_Forwarding">
            <filter>All Logs</filter>
            <send-to-panorama>no</send-to-panorama>
            <send-syslog>
              <member>Sample_Syslog_Profile</member>
            </send-syslog>
          </entry>
        </match-list>
      </userid>

-   name: ironskillet_shared_log_settings_hip_forwarding
    xpath: /config/shared/log-settings
    element: |-
      <hipmatch>
        <match-list>
          <entry name="HIP_Log_Forwarding">
            <filter>All Logs</filter>
            <send-to-panorama>no</send-to-panorama>
            <send-syslog>
              <member>Sample_Syslog_Profile</member>
            </send-syslog>
          </entry>
        </match-list>
      </hipmatch>

-   name: ironskillet_shared_log_settings_ip_tag_forwarding
    xpath: /config/shared/log-settings
    element: |-
      <iptag>
        <match-list>
          <entry name="IP-Tag_Log_Forwarding">
            <send-syslog>
              <member>Sample_Syslog_Profile</member>
            </send-syslog>
            <filter>All Logs</filter>
          </entry>
        </match-list>
      </iptag>