# panos log settings configuration snippets

name: panos_ngfw_log_settings_profiles_10_1
label: PAN_OS NGFW Log Settings Profiles
description: |-
    log forwarding profile object configuration
type: panos
labels:
    collection:
      - IronSkillet 10.1 PAN-OS Snippets

variables:


snippets:
-   name: ironskillet_log_settings_profiles
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/log-settings/profiles
    element: |-
      <entry name="default">
        <match-list>
          <entry name="Traffic_Log_Forwarding">
            <log-type>traffic</log-type>
            <filter>All Logs</filter>
            <send-to-panorama>no</send-to-panorama>
            <send-syslog>
              <member>Sample_Syslog_Profile</member>
            </send-syslog>
          </entry>
          <entry name="Threat_Log_Forwarding">
            <log-type>threat</log-type>
            <filter>All Logs</filter>
            <send-to-panorama>no</send-to-panorama>
            <send-syslog>
              <member>Sample_Syslog_Profile</member>
            </send-syslog>
          </entry>
          <entry name="Wildfire_Log_Forwarding">
            <log-type>wildfire</log-type>
            <filter>All Logs</filter>
            <send-to-panorama>no</send-to-panorama>
            <send-syslog>
              <member>Sample_Syslog_Profile</member>
            </send-syslog>
          </entry>
          <entry name="URL_Log_Forwarding">
            <log-type>url</log-type>
            <filter>All Logs</filter>
            <send-to-panorama>no</send-to-panorama>
            <send-syslog>
              <member>Sample_Syslog_Profile</member>
            </send-syslog>
          </entry>
          <entry name="Data_Log_Forwarding">
            <log-type>data</log-type>
            <filter>All Logs</filter>
            <send-to-panorama>no</send-to-panorama>
            <send-syslog>
              <member>Sample_Syslog_Profile</member>
            </send-syslog>
          </entry>
          <entry name="Tunnel_Log_Forwarding">
            <log-type>tunnel</log-type>
            <filter>All Logs</filter>
            <send-to-panorama>no</send-to-panorama>
            <send-syslog>
              <member>Sample_Syslog_Profile</member>
            </send-syslog>
          </entry>
          <entry name="Auth_Log_Forwarding">
            <log-type>auth</log-type>
            <filter>All Logs</filter>
            <send-to-panorama>no</send-to-panorama>
            <send-syslog>
              <member>Sample_Syslog_Profile</member>
            </send-syslog>
          </entry>
        </match-list>
      </entry>
